import { Environment } from "../../environment";
import { BaseInstruction, BlockId, StoreLocalInstruction } from "../../ir";
import { Place } from "../../ir/core/Place";
import { FunctionIR } from "../../ir/core/FunctionIR";
import { BranchTerminal, JumpTerminal } from "../../ir/core/Terminal";
import { BindingIdentifierInstruction } from "../../ir/instructions/BindingIdentifier";
import { ConditionalExpressionInstruction } from "../../ir/instructions/value/ConditionalExpression";
import { BaseOptimizationPass, OptimizationResult } from "../late-optimizer/OptimizationPass";
import { Phi } from "../ssa/Phi";

/**
 * SSA-phase phi optimization pass (analogous to GCC's pass_phiopt).
 *
 * Detects diamond-shaped CFG patterns where a phi node merges values
 * from two branches that contain only pure instructions, and collapses
 * them into a conditional (ternary) expression.
 *
 * Before:
 * ```
 *   Block A: ... BranchTerminal(test, B, C, D)
 *   Block B: [pure instrs] StoreLocal(x, consValue) → JumpTerminal(D)
 *   Block C: [pure instrs] StoreLocal(x, altValue)  → JumpTerminal(D)
 *   Block D: phi(x: {B→_, C→_})  LoadPhi(phi.place) ...
 * ```
 *
 * After:
 * ```
 *   Block A: [hoisted pure instrs] $cond = test ? consValue : altValue
 *            JumpTerminal(D)
 *   Block D: LoadPhi → rewired to $cond ...
 * ```
 *
 * Operating on phi nodes directly (rather than post-SSA-elimination
 * artifacts) means fewer artifacts are generated by SSA elimination
 * and the ternary result feeds back into subsequent SSA optimization
 * passes (constant propagation, copy propagation, etc.).
 */
export class PhiOptimizationPass extends BaseOptimizationPass {
  constructor(
    protected readonly functionIR: FunctionIR,
    private readonly phis: Set<Phi>,
    private readonly environment: Environment,
  ) {
    super(functionIR);
  }

  protected step(): OptimizationResult {
    let changed = false;

    for (const phi of this.phis) {
      if (this.tryCollapseDiamond(phi)) {
        changed = true;
        // Break after one transformation per step since CFG changed.
        // The base class will re-run step() until no more changes.
        break;
      }
    }

    return { changed };
  }

  private tryCollapseDiamond(phi: Phi): boolean {
    // Only handle 2-operand phis (diamond patterns).
    if (phi.operands.size !== 2) return false;

    const [operandB, operandC] = [...phi.operands.entries()];
    const [blockIdB, placeB] = operandB;
    const [blockIdC, placeC] = operandC;
    const mergeBlockId = phi.blockId;

    const blockB = this.functionIR.blocks.get(blockIdB);
    const blockC = this.functionIR.blocks.get(blockIdC);
    if (!blockB || !blockC) return false;

    // Both branches must jump to the merge block.
    if (!(blockB.terminal instanceof JumpTerminal)) return false;
    if (!(blockC.terminal instanceof JumpTerminal)) return false;
    if (blockB.terminal.target !== mergeBlockId) return false;
    if (blockC.terminal.target !== mergeBlockId) return false;

    // Find the branch block (A) that dominates both B and C.
    // B and C must each have exactly one predecessor (the same block A).
    const predsB = this.functionIR.predecessors.get(blockIdB);
    const predsC = this.functionIR.predecessors.get(blockIdC);
    if (!predsB || predsB.size !== 1) return false;
    if (!predsC || predsC.size !== 1) return false;

    const branchBlockId = [...predsB][0];
    const predsCFirst = [...predsC][0];
    if (predsCFirst === undefined || predsCFirst !== branchBlockId) return false;

    const branchBlock = this.functionIR.blocks.get(branchBlockId);
    if (!branchBlock) return false;

    const terminal = branchBlock.terminal;
    if (!(terminal instanceof BranchTerminal)) return false;
    if (terminal.fallthrough !== mergeBlockId) return false;

    // Determine which operand is consequent and which is alternate.
    let consBlockId: BlockId, altBlockId: BlockId;
    let consOperandPlace, altOperandPlace;

    if (terminal.consequent === blockIdB && terminal.alternate === blockIdC) {
      consBlockId = blockIdB;
      altBlockId = blockIdC;
      consOperandPlace = placeB;
      altOperandPlace = placeC;
    } else if (terminal.consequent === blockIdC && terminal.alternate === blockIdB) {
      consBlockId = blockIdC;
      altBlockId = blockIdB;
      consOperandPlace = placeC;
      altOperandPlace = placeB;
    } else {
      return false;
    }

    const consBlock = this.functionIR.blocks.get(consBlockId)!;
    const altBlock = this.functionIR.blocks.get(altBlockId)!;

    // Find the StoreLocal in each branch that writes to the phi's variable,
    // and extract the value being stored (for the ternary operands).
    const consResult = this.extractPhiStore(consBlock, phi, consOperandPlace);
    const altResult = this.extractPhiStore(altBlock, phi, altOperandPlace);
    if (!consResult || !altResult) return false;

    // All non-phi-store instructions must be pure/hoistable.
    if (!consResult.otherInstrs.every((i) => isHoistable(i, this.environment))) return false;
    if (!altResult.otherInstrs.every((i) => isHoistable(i, this.environment))) return false;

    // === Apply the transformation ===

    // Create the conditional expression instruction.
    const condPlace = this.environment.createPlace(this.environment.createIdentifier());
    const condInstr = this.environment.createInstruction(
      ConditionalExpressionInstruction,
      condPlace,
      undefined,
      terminal.test,
      consResult.valuePlace,
      altResult.valuePlace,
    );

    // Hoist pure instructions from both branches into the branch block,
    // then add the conditional expression.
    branchBlock.instructions.push(...consResult.otherInstrs, ...altResult.otherInstrs, condInstr);

    // Change the branch terminal to a jump to the merge block.
    branchBlock.terminal = new JumpTerminal(terminal.id, mergeBlockId);

    // Rewrite ALL instructions and terminals that reference this phi's place
    // to reference the conditional expression's output place instead.
    // This includes LoadPhiInstructions, but also any other instruction type
    // that was rewritten by SSA renaming to use the phi's place (e.g. StoreLocal).
    const rewriteMap = new Map([[phi.place.identifier, condPlace]]);
    for (const block of this.functionIR.blocks.values()) {
      for (let i = 0; i < block.instructions.length; i++) {
        const rewritten = block.instructions[i].rewrite(rewriteMap);
        if (rewritten !== block.instructions[i]) {
          block.instructions[i] = rewritten;
        }
      }
      if (block.terminal) {
        const rewrittenTerminal = block.terminal.rewrite(rewriteMap);
        if (rewrittenTerminal !== block.terminal) {
          block.terminal = rewrittenTerminal;
        }
      }
    }

    // Update any other phi operands that reference the removed phi's place.
    // This handles nested diamonds where an outer phi reads from an inner phi.
    for (const otherPhi of this.phis) {
      for (const [blockId, operandPlace] of otherPhi.operands) {
        if (operandPlace.identifier.id === phi.place.identifier.id) {
          otherPhi.operands.set(blockId, condPlace);
        }
      }
    }

    // Delete the branch blocks.
    this.functionIR.blocks.delete(consBlockId);
    this.functionIR.blocks.delete(altBlockId);

    // Remove the phi from the set.
    this.phis.delete(phi);

    // Recompute CFG after structural change.
    this.functionIR.recomputeCFG();

    return true;
  }

  /**
   * Extracts the value flowing into a phi from a branch block.
   *
   * Primary path: finds the StoreLocal that writes to the phi's variable
   * and returns the stored value along with the remaining hoistable instructions.
   *
   * Fallback path: when no StoreLocal exists (e.g. after an inner diamond was
   * collapsed into a ternary), the phi operand place itself is the value and
   * all block instructions are candidates for hoisting.
   */
  private extractPhiStore(
    block: { instructions: BaseInstruction[] },
    phi: Phi,
    operandPlace: Place,
  ): { valuePlace: Place; otherInstrs: BaseInstruction[] } | null {
    let storeIndex = -1;

    // Find the last StoreLocal that writes to the phi's variable.
    for (let i = block.instructions.length - 1; i >= 0; i--) {
      const instr = block.instructions[i];
      if (
        instr instanceof StoreLocalInstruction &&
        instr.lval.identifier.declarationId === phi.declarationId
      ) {
        storeIndex = i;
        break;
      }
    }

    if (storeIndex !== -1) {
      const store = block.instructions[storeIndex] as StoreLocalInstruction;

      // Verify this StoreLocal's lval matches the phi operand.
      if (store.lval.identifier.id !== operandPlace.identifier.id) return null;

      // Collect all instructions except the phi StoreLocal.
      const otherInstrs = [
        ...block.instructions.slice(0, storeIndex),
        ...block.instructions.slice(storeIndex + 1),
      ];

      return { valuePlace: store.value, otherInstrs };
    }

    // Fallback: no StoreLocal for this phi variable exists in the block.
    // This happens when an inner diamond was already collapsed — the phi
    // operand place is defined directly by an instruction (e.g. a ternary)
    // rather than through a StoreLocal. Use the operand place as the value
    // and treat all block instructions as hoistable candidates.
    return { valuePlace: operandPlace, otherInstrs: [...block.instructions] };
  }
}

/**
 * Returns true if an instruction can be safely hoisted out of a branch.
 * BindingIdentifierInstruction is treated as hoistable (it's a name binding
 * with no side effects) even though its default isPure is false.
 */
function isHoistable(instr: BaseInstruction, environment: Environment): boolean {
  if (instr instanceof BindingIdentifierInstruction) return true;
  return instr.isPure(environment);
}
