packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^22.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  oxfmt: ^0.27.0
  oxlint: ^1.42.0
  react: ^19.0.0
  react-dom: ^19.2.4
  tailwindcss: ^4.1.18
  tsc-watch: ^7.2.0
  typescript: ^5.7.0
