import type { Operation } from "../../../ir/core/Operation";
import { AwaitExpressionOp } from "../../../ir/ops/async/AwaitExpressionOp";
import { InitializeBindingOp } from "../../../ir/ops/bindings/InitializeBindingOp";
import { LoadBindingOp } from "../../../ir/ops/bindings/LoadBindingOp";
import { StoreBindingOp } from "../../../ir/ops/bindings/StoreBindingOp";
import { CallOp } from "../../../ir/ops/calls/CallOp";
import { ConstructOp } from "../../../ir/ops/calls/ConstructOp";
import { SuperCallOp } from "../../../ir/ops/calls/SuperCallOp";
import { CreateClassOp } from "../../../ir/ops/classes/CreateClassOp";
import { ConstantOp } from "../../../ir/ops/constants/ConstantOp";
import { ReturnTerminatorOp } from "../../../ir/ops/control/ReturnTerminatorOp";
import { ThrowTerminatorOp } from "../../../ir/ops/control/ThrowTerminatorOp";
import { DebuggerOp } from "../../../ir/ops/debugger/DebuggerOp";
import { CreateFunctionOp } from "../../../ir/ops/functions/CreateFunctionOp";
import { YieldExpressionOp } from "../../../ir/ops/generators/YieldExpressionOp";
import { LoadThisOp } from "../../../ir/ops/functions/LoadThisOp";
import { MetaPropertyOp } from "../../../ir/ops/functions/MetaPropertyOp";
import { LoadGlobalOp } from "../../../ir/ops/globals/LoadGlobalOp";
import { RegExpLiteralOp } from "../../../ir/ops/literals/RegExpLiteralOp";
import { TemplateLiteralOp } from "../../../ir/ops/literals/TemplateLiteralOp";
import { ExportDefaultValueOp } from "../../../ir/ops/modules/ExportDefaultValueOp";
import { ImportExpressionOp } from "../../../ir/ops/modules/ImportExpressionOp";
import { JSXElementOp } from "../../../ir/ops/jsx/JSXElementOp";
import { JSXFragmentOp } from "../../../ir/ops/jsx/JSXFragmentOp";
import { BinaryOp } from "../../../ir/ops/operators/BinaryOp";
import { DeleteOp } from "../../../ir/ops/operators/DeleteOp";
import { SequenceExpressionOp } from "../../../ir/ops/operators/SequenceExpressionOp";
import { UnaryOp } from "../../../ir/ops/operators/UnaryOp";
import { ArrayLiteralOp } from "../../../ir/ops/objects/ArrayLiteralOp";
import { ObjectLiteralOp } from "../../../ir/ops/objects/ObjectLiteralOp";
import { DestructureAssignmentOp } from "../../../ir/ops/patterns/DestructureAssignmentOp";
import { DestructureBindingOp } from "../../../ir/ops/patterns/DestructureBindingOp";
import { LoadPropertyOp } from "../../../ir/ops/properties/LoadPropertyOp";
import { LoadPrivatePropertyOp } from "../../../ir/ops/properties/LoadPrivatePropertyOp";
import { HasPrivateNameOp } from "../../../ir/ops/properties/HasPrivateNameOp";
import { StorePrivatePropertyOp } from "../../../ir/ops/properties/StorePrivatePropertyOp";
import { StorePropertyOp } from "../../../ir/ops/properties/StorePropertyOp";
import { StoreSuperPropertyOp } from "../../../ir/ops/properties/StoreSuperPropertyOp";
import { SuperPropertyOp } from "../../../ir/ops/properties/SuperPropertyOp";
import { CopyValueOp } from "../../../ir/ops/values/CopyValueOp";
import type { ESTreeStatement } from "../ast";
import type { CodegenContext } from "../CodegenContext";
import { emitInitializeBindingOp } from "./bindings/emitInitializeBindingOp";
import { emitLoadBindingOp } from "./bindings/emitLoadBindingOp";
import { emitStoreBindingOp } from "./bindings/emitStoreBindingOp";
import { emitCallOp } from "./calls/emitCallOp";
import { emitConstructOp } from "./calls/emitConstructOp";
import { emitSuperCallOp } from "./calls/emitSuperCallOp";
import { emitCreateClassOp } from "./classes/emitCreateClassOp";
import { emitConstantOp } from "./constants/emitConstantOp";
import { emitReturnTerminatorOp } from "./control/emitReturnTerminatorOp";
import { emitThrowTerminatorOp } from "./control/emitThrowTerminatorOp";
import { emitDebuggerOp } from "./debugger/emitDebuggerOp";
import { emitCreateFunctionOp } from "./functions/emitCreateFunctionOp";
import { emitYieldExpressionOp } from "./generators/emitYieldExpressionOp";
import { emitLoadThisOp } from "./functions/emitLoadThisOp";
import { emitMetaPropertyOp } from "./functions/emitMetaPropertyOp";
import { emitLoadGlobalOp } from "./globals/emitLoadGlobalOp";
import { emitRegExpLiteralOp } from "./literals/emitRegExpLiteralOp";
import { emitTemplateLiteralOp } from "./literals/emitTemplateLiteralOp";
import { emitExportDefaultValueOp } from "./modules/emitExportDefaultValueOp";
import { emitImportExpressionOp } from "./modules/emitImportExpressionOp";
import { emitJSXElementOp } from "./jsx/emitJSXElementOp";
import { emitJSXFragmentOp } from "./jsx/emitJSXFragmentOp";
import { emitArrayLiteralOp } from "./objects/emitArrayLiteralOp";
import { emitObjectLiteralOp } from "./objects/emitObjectLiteralOp";
import { emitBinaryOp } from "./operators/emitBinaryOp";
import { emitDeleteOp } from "./operators/emitDeleteOp";
import { emitSequenceExpressionOp } from "./operators/emitSequenceExpressionOp";
import { emitUnaryOp } from "./operators/emitUnaryOp";
import { emitDestructureAssignmentOp } from "./patterns/emitDestructureAssignmentOp";
import { emitDestructureBindingOp } from "./patterns/emitDestructureBindingOp";
import { emitLoadPropertyOp } from "./properties/emitLoadPropertyOp";
import { emitLoadPrivatePropertyOp } from "./properties/emitLoadPrivatePropertyOp";
import { emitHasPrivateNameOp } from "./properties/emitHasPrivateNameOp";
import { emitStorePrivatePropertyOp } from "./properties/emitStorePrivatePropertyOp";
import { emitStorePropertyOp } from "./properties/emitStorePropertyOp";
import { emitStoreSuperPropertyOp } from "./properties/emitStoreSuperPropertyOp";
import { emitSuperPropertyOp } from "./properties/emitSuperPropertyOp";
import { emitAwaitExpressionOp } from "./async/emitAwaitExpressionOp";
import { emitCopyValueOp } from "./values/emitCopyValueOp";

export function emitOperation(context: CodegenContext, op: Operation): ESTreeStatement[] {
  if (op instanceof ConstantOp) return emitConstantOp(context, op);
  if (op instanceof AwaitExpressionOp) return emitAwaitExpressionOp(context, op);
  if (op instanceof DebuggerOp) return emitDebuggerOp(context, op);
  if (op instanceof InitializeBindingOp) return emitInitializeBindingOp(context, op);
  if (op instanceof LoadBindingOp) return emitLoadBindingOp(context, op);
  if (op instanceof StoreBindingOp) return emitStoreBindingOp(context, op);
  if (op instanceof CallOp) return emitCallOp(context, op);
  if (op instanceof ConstructOp) return emitConstructOp(context, op);
  if (op instanceof SuperCallOp) return emitSuperCallOp(context, op);
  if (op instanceof CreateClassOp) return emitCreateClassOp(context, op);
  if (op instanceof CreateFunctionOp) return emitCreateFunctionOp(context, op);
  if (op instanceof YieldExpressionOp) return emitYieldExpressionOp(context, op);
  if (op instanceof LoadThisOp) return emitLoadThisOp(context, op);
  if (op instanceof MetaPropertyOp) return emitMetaPropertyOp(context, op);
  if (op instanceof LoadGlobalOp) return emitLoadGlobalOp(context, op);
  if (op instanceof RegExpLiteralOp) return emitRegExpLiteralOp(context, op);
  if (op instanceof TemplateLiteralOp) return emitTemplateLiteralOp(context, op);
  if (op instanceof ExportDefaultValueOp) return emitExportDefaultValueOp(context, op);
  if (op instanceof ImportExpressionOp) return emitImportExpressionOp(context, op);
  if (op instanceof JSXElementOp) return emitJSXElementOp(context, op);
  if (op instanceof JSXFragmentOp) return emitJSXFragmentOp(context, op);
  if (op instanceof ArrayLiteralOp) return emitArrayLiteralOp(context, op);
  if (op instanceof ObjectLiteralOp) return emitObjectLiteralOp(context, op);
  if (op instanceof BinaryOp) return emitBinaryOp(context, op);
  if (op instanceof DeleteOp) return emitDeleteOp(context, op);
  if (op instanceof SequenceExpressionOp) return emitSequenceExpressionOp(context, op);
  if (op instanceof UnaryOp) return emitUnaryOp(context, op);
  if (op instanceof DestructureBindingOp) return emitDestructureBindingOp(context, op);
  if (op instanceof DestructureAssignmentOp) return emitDestructureAssignmentOp(context, op);
  if (op instanceof ReturnTerminatorOp) return emitReturnTerminatorOp(context, op);
  if (op instanceof ThrowTerminatorOp) return emitThrowTerminatorOp(context, op);
  if (op instanceof LoadPropertyOp) return emitLoadPropertyOp(context, op);
  if (op instanceof LoadPrivatePropertyOp) return emitLoadPrivatePropertyOp(context, op);
  if (op instanceof HasPrivateNameOp) return emitHasPrivateNameOp(context, op);
  if (op instanceof StorePropertyOp) return emitStorePropertyOp(context, op);
  if (op instanceof StorePrivatePropertyOp) return emitStorePrivatePropertyOp(context, op);
  if (op instanceof StoreSuperPropertyOp) return emitStoreSuperPropertyOp(context, op);
  if (op instanceof SuperPropertyOp) return emitSuperPropertyOp(context, op);
  if (op instanceof CopyValueOp) return emitCopyValueOp(context, op);

  throw new Error(`Unsupported JS codegen op: ${op.constructor.name}`);
}
